name: Snyk Security
description: "Snyk Security Action to check for security issues in the code and dependencies."

inputs:
  SNYK_TOKEN:
    description: "The Snyk API token to use for the build"
    required: true
  SNYK_ORG:
    description: "The Snyk organization to use for the build"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Snyk CLI to check for security issues
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
        SNYK_ORG: ${{ inputs.SNYK_ORG }}

    - name: Snyk Auth
      shell: bash
      run: snyk auth ${{ inputs.SNYK_TOKEN }}

    - name: Snyk Code test
      shell: bash
      run: snyk code test --org=${{ inputs.SNYK_ORG }} --sarif --sarif-file-output=snyk-code.sarif

    - name: Snyk Open Source monitor
      shell: bash
      run: snyk monitor --org=${{ inputs.SNYK_ORG }} --all-projects || true

    - name: Snyk IaC test and report
      shell: bash
      run: snyk iac test --org=${{ inputs.SNYK_ORG }} --report || true

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk-code.sarif

