name: On Push

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["17", "21"]
    steps:
      - name: Init
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/init@master
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Build
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/build-gradle@master
        with:
          JAVA_VERSION: ${{ matrix.java-version }}
