name: On Pull

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/init@master
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Build
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/build-gradle@master
