name: Push to Master

on:
  push:
    branches:
      - master

jobs:
  pull_request_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/init@master
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Build
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/build-gradle@master

      - name: Synk Security
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/snyk@master
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
