name: On Release

on:
  release:
    types: [created]

jobs:
  release:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/init@master
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Set TAG_VERSION
        id: set_version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update Version
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/update-version@master
        with:
          TAG_VERSION: ${{ env.TAG_VERSION }}
          PUSH_CHANGES: "true"

      - name: Build
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/build-gradle@master

      - name: Synk Security
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/snyk@master
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}

      - name: Update Release
        uses: Thesam1798/tutorial-mod-minecraft/.github/actions/update-release@master
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
